Team.create(name: "Qatar" )
Team.create(name: "Ecuador")
Team.create(name: "Senegal")
Team.create(name: "Holanda")
Team.create(name: "Inglaterra")
Team.create(name: "Iran")
Team.create(name: "USA")
Team.create(name: "Argentina")
Team.create(name: "Mexico")
Team.create(name: "Polonia")
Team.create(name: "Francia")
Team.create(name: "Brasil")

